#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

# Attempt to set APP_HOME
APP_HOME=$( cd "${BASH_SOURCE[0]%/*}/.." && pwd )

# Add default JVM options here.
DEFAULT_JVM_OPTS=""

exec "$APP_HOME/gradlew" "$@"
